<a href="https://colab.research.google.com/github/umeshnandargi/Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
np.random.rand(3,3,4)

array([[[0.44980309, 0.02696255, 0.70438017, 0.84634564],
        [0.60436694, 0.32979159, 0.06320418, 0.99039269],
        [0.00276271, 0.79055602, 0.87166304, 0.00916631]],

       [[0.08479446, 0.55849533, 0.13769484, 0.38529548],
        [0.18786122, 0.38542133, 0.96392823, 0.78082457],
        [0.98449954, 0.15016394, 0.06467879, 0.80313102]],

       [[0.3259256 , 0.28983455, 0.09036609, 0.86069522],
        [0.28776144, 0.39221092, 0.54356598, 0.092619  ],
        [0.23965199, 0.5870661 , 0.74456932, 0.54144032]]])

In [2]:
import torch

tensor_3d = torch.zeros(2, 3,3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

#Tensor operations

In [ ]:
my_tesnor = torch.arange(10)


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

### Reshape

In [ ]:
my_tesnor.reshape([5,2])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_tesnor.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

##Slices

In [ ]:
x = my_tesnor[1:].reshape(3,3)
print(x)
x_col_slice = x[:,1]
print(x_col_slice)
x_col = x_col_slice.reshape(3,1)
print(x_col)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 5, 8])
tensor([[2],
        [5],
        [8]])


## Tensor Math operations

In [9]:
a = torch.tensor([1,2,3,4,5])
b = torch.arange(6,11)
a,b

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [17]:
#Addition
a + b
torch.add(a,b)

tensor([ 7,  9, 11, 13, 15])

In [21]:
# Subtraction
a-b
torch.sub(a,b)

tensor([-5, -5, -5, -5, -5])

In [24]:
# Multiplication

a*b
torch.mul(a,b)

tensor([ 6, 14, 24, 36, 50])

In [27]:
# Division
a/b
torch.div(a,b)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [32]:
# Remainder modulus

b % a
torch.remainder(b, a)

tensor([0, 1, 2, 1, 0])

In [36]:
# exponent
b ** a
torch.pow(b,a )

tensor([     6,     49,    512,   6561, 100000])

In [44]:
# Reassignment
a = a+b
a.add_(b)

tensor([ 79,  93, 107, 121, 135])